version: '3'
services:

  app:
    container_name: zen-app
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
    depends_on:
      - mongo
    environment:
        - MONGOURL=mongodb://mongo:27017/zen
        - DOCKER=true

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'